# Generated by Django 5.2.5 on 2026-02-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='upi_reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
