# Generated by Django 5.2.10 on 2026-03-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_order_upi_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram (kg)'), ('litre', 'Litre (L)'), ('piece', 'Piece'), ('packet', 'Packet'), ('dozen', 'Dozen'), ('gram', 'Gram (g)')], default='kg', max_length=20),
        ),
    ]
